### PR TITLE
Allow font customization

### PR DESCRIPTION
**Pull request by shagedorn**
The author has rejected multiple PRs that allow similar types of customization, so I won't bother opening one...

### CODE REVIEW

**Comment by mollidor** [comment]
Has this been opened before or after checking `UIAppearance`?

**Comment by shagedorn** [comment]
Before, will try out appearance first before merging/using this one.

**Comment by shagedorn** [comment]
We cannot distinguish between the number keys and the done button, but that's probably a worthy tradeoff for a 0 diff from the original repo. Will close this one.

**Comment by shagedorn** [comment]
Will restore this – `UIAppearance` works in the simulator, but not on device. I assume this is because the `inputView` runs as an extension and hence in a separate process.

**Pull request closed without merging**
